name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - "packages/auth/**"

permissions:
  contents: write

defaults:
  run:
    working-directory: packages/auth

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

      - name: Deploy auth to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: auth/latest
          keep_files: true

