name: deploy-marketing

on:
  push:
    branches:
      - main
    paths:
      - "packages/marketing/**"

permissions:
  contents: write

defaults:
  run:
    working-directory: packages/marketing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build

      - name: Deploy marketing to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: marketing/latest
